version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    automerged_updates:
      - match:
          dependency_name: "gofiber/fiber/*"