// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "AGPLv3"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/contents": {
            "get": {
                "tags": [
                    "contents"
                ],
                "summary": "Fetch contents",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "enum": [
                                "rss",
                                "vimeo",
                                "youtube"
                            ],
                            "type": "string"
                        },
                        "description": "filter contents by source types",
                        "name": "sourceTypes",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "description": "filter contents by source id",
                        "name": "sources",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Fetch page",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Pagination"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Items": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/Content"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/JSONError"
                        }
                    }
                }
            }
        },
        "/contents/{contentId}": {
            "get": {
                "tags": [
                    "contents"
                ],
                "summary": "Get one content by id",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Content"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/JSONError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/JSONError"
                        }
                    }
                }
            }
        },
        "/langs": {
            "get": {
                "tags": [
                    "langs"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/Lang"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/JSONError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "langs"
                ],
                "parameters": [
                    {
                        "description": "Create body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/lang.CreateBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Lang"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/JSONError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/JSONError"
                        }
                    }
                }
            }
        },
        "/langs/{isoCode}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "langs"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Lang ISO Code",
                        "name": "isoCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/JSONMessage"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/JSONError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/JSONError"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "langs"
                ],
                "parameters": [
                    {
                        "description": "Update body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/lang.UpdateBody"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Lang ISO Code",
                        "name": "isoCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Lang"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/JSONError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/JSONError"
                        }
                    }
                }
            }
        },
        "/refresh": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "refresh"
                ],
                "summary": "Refresh sources by there types",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "enum": [
                                "rss",
                                "vimeo",
                                "youtube"
                            ],
                            "type": "string"
                        },
                        "description": "Type of sources to refresh",
                        "name": "types",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/Content"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/JSONError"
                        }
                    }
                }
            }
        },
        "/refresh/sync-feedly": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "refresh"
                ],
                "summary": "Query sources used in feedly and add missing ones in Scribe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/Source"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/JSONError"
                        }
                    }
                }
            }
        },
        "/refresh/{sourceID}": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "refresh"
                ],
                "summary": "Refresh a given source",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Source ID",
                        "name": "sourceID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Will override content attributes",
                        "name": "force",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/Source"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/JSONError"
                        }
                    }
                }
            }
        },
        "/sources": {
            "get": {
                "tags": [
                    "sources"
                ],
                "summary": "Fetch all sources",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "enum": [
                                "rss",
                                "vimeo",
                                "youtube"
                            ],
                            "type": "string"
                        },
                        "description": "Filter by source types",
                        "name": "types",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/Source"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/JSONError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "sources"
                ],
                "summary": "Add a new source",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/source.CreateBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Source"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/JSONError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/JSONError"
                        }
                    }
                }
            }
        },
        "/sources/order": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "sources"
                ],
                "summary": "Update orders of the sources",
                "parameters": [
                    {
                        "description": "Update body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/source.UpdateBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/Source"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/JSONError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/JSONError"
                        }
                    }
                }
            }
        },
        "/sources/{sourceID}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "sources"
                ],
                "summary": "Delete a source",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the source",
                        "name": "sourceID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/JSONMessage"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/JSONError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/JSONError"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "sources"
                ],
                "summary": "Update a source",
                "parameters": [
                    {
                        "description": "Update body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/source.UpdateBody"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "ID of the source",
                        "name": "sourceID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Source"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/JSONError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Content": {
            "type": "object",
            "properties": {
                "author": {
                    "description": "For feedly article",
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "contentId": {
                    "description": "Youtube or Vimeo ID or Feedly ID",
                    "type": "string"
                },
                "contentUrl": {
                    "description": "Youtube or Vimeo video url or article URL",
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "publishedAt": {
                    "type": "string"
                },
                "rawContent": {
                    "type": "string"
                },
                "rawSummary": {
                    "type": "string"
                },
                "source": {
                    "$ref": "#/definitions/Source"
                },
                "summary": {
                    "type": "string"
                },
                "thumbnailUrl": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "JSONError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "JSONMessage": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "Lang": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "imageUrl": {
                    "type": "string"
                },
                "isoCode": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "Pagination": {
            "type": "object",
            "properties": {
                "items": {},
                "page": {
                    "type": "integer"
                },
                "perPage": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                },
                "totalResults": {
                    "type": "integer"
                }
            }
        },
        "Source": {
            "type": "object",
            "properties": {
                "coverUrl": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "iconUrl": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lang": {
                    "$ref": "#/definitions/Lang"
                },
                "order": {
                    "type": "integer"
                },
                "publishedAt": {
                    "type": "string"
                },
                "refreshedAt": {
                    "type": "string"
                },
                "shortTitle": {
                    "type": "string"
                },
                "skateSource": {
                    "type": "boolean"
                },
                "sourceId": {
                    "description": "Vimeo, Youtube or Feedly ID, depending on the type",
                    "type": "string"
                },
                "sourceType": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "websiteUrl": {
                    "type": "string"
                }
            }
        },
        "lang.CreateBody": {
            "type": "object",
            "required": [
                "imageURL",
                "isoCode"
            ],
            "properties": {
                "imageURL": {
                    "type": "string"
                },
                "isoCode": {
                    "type": "string"
                }
            }
        },
        "lang.UpdateBody": {
            "type": "object",
            "required": [
                "imageURL"
            ],
            "properties": {
                "imageURL": {
                    "type": "string"
                }
            }
        },
        "source.CreateBody": {
            "type": "object",
            "required": [
                "lang",
                "type"
            ],
            "properties": {
                "isSkateSource": {
                    "type": "boolean"
                },
                "lang": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "vimeo",
                        "youtube"
                    ]
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "source.UpdateBody": {
            "type": "object",
            "properties": {
                "coverURL": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "iconURL": {
                    "type": "string"
                },
                "isSkateSource": {
                    "type": "boolean"
                },
                "lang": {
                    "type": "string"
                },
                "shortTitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "websiteURL": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Scribe API",
	Description:      "Document for the Scribe API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
