basePath: /
consumes:
- application/json
definitions:
  "":
    properties:
      items: {}
      page:
        type: integer
      perPage:
        type: integer
      totalPages:
        type: integer
      totalResults:
        type: integer
    type: object
  Content:
    properties:
      author:
        description: For feedly article
        type: string
      content:
        type: string
      contentId:
        description: Youtube or Vimeo ID or Feedly ID
        type: string
      contentUrl:
        description: Youtube or Vimeo video url or article URL
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: string
      publishedAt:
        type: string
      rawContent:
        type: string
      rawSummary:
        type: string
      sourceId:
        type: integer
      summary:
        type: string
      thumbnailUrl:
        type: string
      title:
        type: string
      type:
        type: string
    type: object
  JSONError:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  JSONMessage:
    properties:
      message:
        type: string
    type: object
  Lang:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      imageUrl:
        type: string
      isoCode:
        type: string
      updatedAt:
        type: string
    type: object
  Source:
    properties:
      coverUrl:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      description:
        type: string
      iconUrl:
        type: string
      id:
        type: integer
      lang:
        type: string
      order:
        type: integer
      publishedAt:
        type: string
      refreshedAt:
        type: string
      shortTitle:
        type: string
      skateSource:
        type: boolean
      sourceId:
        description: Vimeo, Youtube or Feedly ID, depending on the type
        type: string
      sourceType:
        type: string
      title:
        type: string
      updatedAt:
        type: string
      websiteUrl:
        type: string
    type: object
  lang.CreateBody:
    properties:
      imageURL:
        type: string
      isoCode:
        type: string
    required:
    - imageURL
    - isoCode
    type: object
  lang.UpdateBody:
    properties:
      imageURL:
        type: string
    required:
    - imageURL
    type: object
  source.CreateBody:
    properties:
      isSkateSource:
        type: boolean
      lang:
        type: string
      type:
        enum:
        - vimeo
        - youtube
        type: string
      url:
        type: string
    required:
    - lang
    - type
    type: object
  source.UpdateBody:
    properties:
      coverURL:
        type: string
      description:
        type: string
      iconURL:
        type: string
      isSkateSource:
        type: boolean
      lang:
        type: string
      shortTitle:
        type: string
      title:
        type: string
      websiteURL:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Document for the Scribe API
  license:
    name: AGPLv3
  title: Scribe API
  version: "1.0"
paths:
  /contents:
    get:
      parameters:
      - description: filter contents by source types
        in: query
        items:
          enum:
          - rss
          - vimeo
          - youtube
          type: string
        name: sourceTypes
        type: array
      - description: filter contents by source id
        in: query
        items:
          type: integer
        name: sources
        type: array
      - description: Fetch page
        in: query
        minimum: 1
        name: page
        type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/'
            - properties:
                Items:
                  items:
                    $ref: '#/definitions/Content'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/JSONError'
      security:
      - ApiKeyAuth: []
      summary: Fetch contents
      tags:
      - contents
  /langs:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/Lang'
              type: array
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/JSONError'
      tags:
      - langs
    post:
      parameters:
      - description: Create body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/lang.CreateBody'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Lang'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/JSONError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/JSONError'
      security:
      - ApiKeyAuth: []
      tags:
      - langs
  /langs/{isoCode}:
    delete:
      parameters:
      - description: Lang ISO Code
        in: path
        name: isoCode
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/JSONMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/JSONError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/JSONError'
      security:
      - ApiKeyAuth: []
      tags:
      - langs
    patch:
      parameters:
      - description: Update body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/lang.UpdateBody'
      - description: Lang ISO Code
        in: path
        name: isoCode
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Lang'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/JSONError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/JSONError'
      security:
      - ApiKeyAuth: []
      tags:
      - langs
  /refresh:
    patch:
      parameters:
      - description: Type of sources to refresh
        in: query
        items:
          enum:
          - rss
          - vimeo
          - youtube
          type: string
        name: types
        required: true
        type: array
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/Content'
              type: array
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/JSONError'
      security:
      - ApiKeyAuth: []
      summary: Refresh sources by there types
      tags:
      - refresh
  /refresh/{sourceID}:
    patch:
      parameters:
      - description: Source ID
        in: path
        name: sourceID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/Source'
              type: array
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/JSONError'
      security:
      - ApiKeyAuth: []
      summary: Refresh a given source
      tags:
      - refresh
  /sources:
    get:
      parameters:
      - description: Filter by source types
        in: query
        items:
          enum:
          - rss
          - vimeo
          - youtube
          type: string
        name: types
        type: array
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/Source'
              type: array
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/JSONError'
      summary: Fetch all sources
      tags:
      - sources
    post:
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/source.CreateBody'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Source'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/JSONError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/JSONError'
      security:
      - ApiKeyAuth: []
      summary: Add a new source
      tags:
      - sources
  /sources/{sourceID}:
    delete:
      parameters:
      - description: ID of the source
        in: path
        name: sourceID
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/JSONMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/JSONError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/JSONError'
      security:
      - ApiKeyAuth: []
      summary: Delete a source
      tags:
      - sources
    patch:
      parameters:
      - description: Update body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/source.UpdateBody'
      - description: ID of the source
        in: path
        name: sourceID
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Source'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/JSONError'
      security:
      - ApiKeyAuth: []
      summary: Update a source
      tags:
      - sources
  /sources/order:
    patch:
      parameters:
      - description: Update body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/source.UpdateBody'
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/Source'
              type: array
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/JSONError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/JSONError'
      security:
      - ApiKeyAuth: []
      summary: Update orders of the sources
      tags:
      - sources
  /sources/sync-feedly:
    patch:
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/Source'
              type: array
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/JSONError'
      security:
      - ApiKeyAuth: []
      summary: Query sources used in feedly and add missing ones in Scribe
      tags:
      - refresh
produces:
- application/json
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
