on: [push, pull_request]
name: Checkup 
jobs:
  Golint:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3
      - name: Run Golint
        uses: reviewdog/action-golangci-lint@v1
        with:
          golangci_lint_flags: "--tests=false"

  Gosec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        Project: ['scribe','utils']
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3
      - name: Run Gosec
        uses: securego/gosec@master
        with:
          args: ./${{matrix.Project}}/...