on:
  push:
    branches:
      - 'main'

name: Deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Deploy to Clever Cloud
        uses: 47ng/actions-clever-cloud@v1.2.0
        with:
          appID: ${{ secrets.SCRIBE_APP_ID }}
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}